kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins-jmeter
  labels:
    app.kubernetes.io/part-of: cloud-barista
    app.kubernetes.io/component: jenkins-jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: cloud-barista
      app.kubernetes.io/component: jenkins-jmeter
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: cloud-barista
        app.kubernetes.io/component: jenkins-jmeter
    spec:
      containers:
        - name: jenkins
          image: honester/jenkins-jmeter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: JENKINS_USERNAME
              value: admin
            - name: JENKINS_PASSWORD
              value: admin1234
            - name: JENKINS_HOME
              value: /bitnami/jenkins/home
            - name: DISABLE_JENKINS_INITIALIZATION
              value: "no"
            - name: JENKINS_EXTERNAL_HTTP_PORT_NUMBER
              value: "80"
            - name: JENKINS_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
          #resources:
          #  requests:
          #    memory: "64Mi"
          #    cpu: "20m"
          #  limits:
          #    memory: "64Mi"
          #    cpu: "20m"
          volumeMounts:
            - name: jenkins-data-volume
              mountPath: /bitnami/jenkins
      volumes:
        - name: jenkins-data-volume
          emptyDir: {}
      nodeSelector:
        "kubernetes.io/os": linux
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-jmeter
  labels:
    app.kubernetes.io/part-of: cloud-barista
    app.kubernetes.io/component: jenkins-jmeter
spec:
  type: NodePort
  ports:
    - name: jenkins
      nodePort: 30084
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/part-of: cloud-barista
    app.kubernetes.io/component: jenkins-jmeter
